In [1]:
import numpy as np

In [2]:
a=np.array([1,132,1.549,1.919,2.571])

In [3]:
np.floor(a)

array([  1., 132.,   1.,   1.,   2.])

In [4]:
np.ceil(a)

array([  1., 132.,   2.,   2.,   3.])

In [5]:
np.round(a,decimals=2)

array([  1.  , 132.  ,   1.55,   1.92,   2.57])