In [1]:
import numpy as np

In [2]:
np.ones(40,dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [3]:
np.ones(20,dtype=np.int16)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=int16)

In [4]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [5]:
np.zeros(4).shape

(4,)

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.zeros(9).reshape(3,-1)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.zeros((3,3)).shape

(3, 3)

In [10]:
np.empty(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

you can create an array with range of elements using np.arrange()

In [11]:
list(range(1,10,1))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(1,6,2)

array([1, 3, 5])

In [15]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

use np.linespace() to create array with values that are spaced linearly in a specified interval

In [17]:
np.linspace(0,0.5,100) #(start,end,no_of_data)

array([0.        , 0.00505051, 0.01010101, 0.01515152, 0.02020202,
       0.02525253, 0.03030303, 0.03535354, 0.04040404, 0.04545455,
       0.05050505, 0.05555556, 0.06060606, 0.06565657, 0.07070707,
       0.07575758, 0.08080808, 0.08585859, 0.09090909, 0.0959596 ,
       0.1010101 , 0.10606061, 0.11111111, 0.11616162, 0.12121212,
       0.12626263, 0.13131313, 0.13636364, 0.14141414, 0.14646465,
       0.15151515, 0.15656566, 0.16161616, 0.16666667, 0.17171717,
       0.17676768, 0.18181818, 0.18686869, 0.19191919, 0.1969697 ,
       0.2020202 , 0.20707071, 0.21212121, 0.21717172, 0.22222222,
       0.22727273, 0.23232323, 0.23737374, 0.24242424, 0.24747475,
       0.25252525, 0.25757576, 0.26262626, 0.26767677, 0.27272727,
       0.27777778, 0.28282828, 0.28787879, 0.29292929, 0.2979798 ,
       0.3030303 , 0.30808081, 0.31313131, 0.31818182, 0.32323232,
       0.32828283, 0.33333333, 0.33838384, 0.34343434, 0.34848485,
       0.35353535, 0.35858586, 0.36363636, 0.36868687, 0.37373

Concat and sorting two numpy array

In [18]:
arr=np.array([-1,-11,4,77,2,-99,3])

In [19]:
np.sort(arr,axis=-1)[::-1]

array([ 77,   4,   3,   2,  -1, -11, -99])

In [20]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [21]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
a+b

array([ 6,  8, 10, 12])