In [1]:
import numpy as np

In [2]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [3]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
np.full((3,2),7)

array([[7, 7],
       [7, 7],
       [7, 7]])

In [5]:
np.full((4,4),0.6)

array([[0.6, 0.6, 0.6, 0.6],
       [0.6, 0.6, 0.6, 0.6],
       [0.6, 0.6, 0.6, 0.6],
       [0.6, 0.6, 0.6, 0.6]])