In [8]:
import numpy as np

In [9]:
a=np.array([1,2])
b=np.array([4,2])

In [10]:
a+b

array([5, 4])

In [11]:
a-b

array([-3,  0])

In [12]:
a*b

array([4, 4])

In [13]:
a/b

array([0.25, 1.  ])

In [14]:
a=np.array([1,2])
b=np.array([4,8])
a**b

array([  1, 256])