In [1]:
import numpy as np

In [2]:
a=np.array([[4,8,5],[9,3,1]])

In [3]:
a

array([[4, 8, 5],
       [9, 3, 1]])

In [4]:
a.flatten()

array([4, 8, 5, 9, 3, 1])

In [6]:
a.ravel()

array([4, 8, 5, 9, 3, 1])

In [7]:
a.min()

1

Transpose

In [9]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [11]:
b=np.array([1,2,3]).reshape(1,3)

In [12]:
b.shape

(1, 3)

In [13]:
b

array([[1, 2, 3]])