In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3],[4,5,6]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a.sum()

21

In [5]:
a.sum(axis=0)

array([5, 7, 9])

In [6]:
a.sum(axis=1)

array([ 6, 15])