In [2]:
import numpy as np

In [3]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a[1,2]

6

In [5]:
a[0,0]

1

In [6]:
a[0,1:]

array([2, 3])

In [7]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

In [10]:
np.random.seed(5)
np.random.randint(0,10,(3,2))

array([[3, 6],
       [6, 0],
       [9, 8]])

In [12]:
np.random.seed(5)
np.random.uniform(0,10,(3,2))#uniform x belongs to [0,10)

array([[2.21993171, 8.70732306],
       [2.06719155, 9.18610908],
       [4.88411189, 6.11743863]])

Normal Distribution

In [13]:
np.random.normal(10,2,(3,2)) 

array([[10.21921968, 13.16496223],
       [ 8.18153519,  8.81672668],
       [10.37520645,  9.34026008]])

In [14]:
np.random.randn(3,2)

array([[-1.19276461, -0.20487651],
       [-0.35882895,  0.6034716 ],
       [-1.66478853, -0.70017904]])