In [15]:
import numpy as np

In [16]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
a[1,2]

6

In [18]:
a[0,0]

1

In [19]:
a[0,1:]

array([2, 3])

In [20]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
a[1:,1:]

array([[5, 6],
       [8, 9]])